from sqlalchemy import Column, Integer, String, FLOAT, DateTime

from app.db.base_class import Base


class Indicator(Base):
    id = Column(Integer, primary_key=True, index=True)
    period = Column(DateTime, nullable=False)
    country = Column(String(256), nullable=False)
    bci = Column(FLOAT(precision=32), nullable=True)
    bci_nor = Column(FLOAT(precision=32), nullable=True)
    bci_pc = Column(FLOAT(precision=32), nullable=True)
    cci = Column(FLOAT(precision=32), nullable=True)
    cci_nor = Column(FLOAT(precision=32), nullable=True)
    cci_pc = Column(FLOAT(precision=32), nullable=True)
    government_reserves = Column(FLOAT(precision=32), nullable=True)
    government_reserves_nor = Column(FLOAT(precision=32), nullable=True)
    government_reserves_pc = Column(FLOAT(precision=32), nullable=True)
    industrial_production = Column(FLOAT(precision=32), nullable=True)
    industrial_production_nor = Column(FLOAT(precision=32), nullable=True)
    industrial_production_pc = Column(FLOAT(precision=32), nullable=True)
    inflation_growth_rate = Column(FLOAT(precision=32), nullable=True)
    inflation_growth_rate_nor = Column(FLOAT(precision=32), nullable=True)
    inflation_growth_rate_pc = Column(FLOAT(precision=32), nullable=True)
    long_term_interest = Column(FLOAT(precision=32), nullable=True)
    long_term_interest_nor = Column(FLOAT(precision=32), nullable=True)
    long_term_interest_pc = Column(FLOAT(precision=32), nullable=True)
    ppi_growth_rate = Column(FLOAT(precision=32), nullable=True)
    ppi_growth_rate_nor = Column(FLOAT(precision=32), nullable=True)
    ppi_growth_rate_pc = Column(FLOAT(precision=32), nullable=True)
    qgdp = Column(FLOAT(precision=32), nullable=True)
    qgdp_nor = Column(FLOAT(precision=32), nullable=True)
    qgdp_pc = Column(FLOAT(precision=32), nullable=True)
    share_price = Column(FLOAT(precision=32), nullable=True)
    share_price_nor = Column(FLOAT(precision=32), nullable=True)
    share_price_pc = Column(FLOAT(precision=32), nullable=True)
    short_term_interest = Column(FLOAT(precision=32), nullable=True)
    short_term_interest_nor = Column(FLOAT(precision=32), nullable=True)
    short_term_interest_pc = Column(FLOAT(precision=32), nullable=True)
    trade_in_goods = Column(FLOAT(precision=32), nullable=True)
    trade_in_goods_nor = Column(FLOAT(precision=32), nullable=True)
    trade_in_goods_pc = Column(FLOAT(precision=32), nullable=True)
    unemployment_rate = Column(FLOAT(precision=32), nullable=True)
    unemployment_rate_nor = Column(FLOAT(precision=32), nullable=True)
    unemployment_rate_pc = Column(FLOAT(precision=32), nullable=True)
    contraction_prob = Column(FLOAT(precision=32), nullable=True)
    expension_prob = Column(FLOAT(precision=32), nullable=True)
    peak_prob = Column(FLOAT(precision=32), nullable=True)
    trough_prob = Column(FLOAT(precision=32), nullable=True)
    prediction = Column(String(256), nullable=True)
