"""Init migration

Revision ID: 17246f04cfd3
Revises: 
Create Date: 2023-07-10 20:57:42.054518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17246f04cfd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('bci', sa.FLOAT(precision=32), nullable=True),
    sa.Column('bci_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('bci_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('cci', sa.FLOAT(precision=32), nullable=True),
    sa.Column('cci_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('cci_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('government_reserves', sa.FLOAT(precision=32), nullable=True),
    sa.Column('government_reserves_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('government_reserves_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('industrial_production', sa.FLOAT(precision=32), nullable=True),
    sa.Column('industrial_production_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('industrial_production_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('inflation_growth_rate', sa.FLOAT(precision=32), nullable=True),
    sa.Column('inflation_growth_rate_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('inflation_growth_rate_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('long_term_interest', sa.FLOAT(precision=32), nullable=True),
    sa.Column('long_term_interest_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('long_term_interest_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('ppi_growth_rate', sa.FLOAT(precision=32), nullable=True),
    sa.Column('ppi_growth_rate_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('ppi_growth_rate_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('qgdp', sa.FLOAT(precision=32), nullable=True),
    sa.Column('qgdp_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('qgdp_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('share_price', sa.FLOAT(precision=32), nullable=True),
    sa.Column('share_price_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('share_price_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('short_term_interest', sa.FLOAT(precision=32), nullable=True),
    sa.Column('short_term_interest_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('short_term_interest_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('trade_in_goods', sa.FLOAT(precision=32), nullable=True),
    sa.Column('trade_in_goods_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('trade_in_goods_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('unemployment_rate', sa.FLOAT(precision=32), nullable=True),
    sa.Column('unemployment_rate_nor', sa.FLOAT(precision=32), nullable=True),
    sa.Column('unemployment_rate_pc', sa.FLOAT(precision=32), nullable=True),
    sa.Column('contraction_prob', sa.FLOAT(precision=32), nullable=True),
    sa.Column('expension_prob', sa.FLOAT(precision=32), nullable=True),
    sa.Column('peak_prob', sa.FLOAT(precision=32), nullable=True),
    sa.Column('trough_prob', sa.FLOAT(precision=32), nullable=True),
    sa.Column('prediction', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_country'), 'indicator', ['country'], unique=False)
    op.create_index(op.f('ix_indicator_id'), 'indicator', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_period'), 'indicator', ['period'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email_notification', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_indicator_period'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_id'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_country'), table_name='indicator')
    op.drop_table('indicator')
    # ### end Alembic commands ###
