"""Init migration

Revision ID: 56502b1cf909
Revises: 
Create Date: 2023-04-05 19:27:28.564687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56502b1cf909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlyindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('bci', sa.FLOAT(precision=32), nullable=True),
    sa.Column('cci', sa.FLOAT(precision=32), nullable=True),
    sa.Column('government_reserves', sa.FLOAT(precision=32), nullable=True),
    sa.Column('industrial_production', sa.FLOAT(precision=32), nullable=True),
    sa.Column('inflation_index', sa.FLOAT(precision=32), nullable=True),
    sa.Column('inflation_growth_rate', sa.FLOAT(precision=32), nullable=True),
    sa.Column('long_term_interest', sa.FLOAT(precision=32), nullable=True),
    sa.Column('ppi_index', sa.FLOAT(precision=32), nullable=True),
    sa.Column('ppi_growth_rate', sa.FLOAT(precision=32), nullable=True),
    sa.Column('share_price', sa.FLOAT(precision=32), nullable=True),
    sa.Column('short_term_interest', sa.FLOAT(precision=32), nullable=True),
    sa.Column('trade_in_goods', sa.FLOAT(precision=32), nullable=True),
    sa.Column('unemployment_rate', sa.FLOAT(precision=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthlyindicator_id'), 'monthlyindicator', ['id'], unique=False)
    op.create_table('quarterlyindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('qgdp', sa.FLOAT(precision=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarterlyindicator_id'), 'quarterlyindicator', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarterlyindicator_id'), table_name='quarterlyindicator')
    op.drop_table('quarterlyindicator')
    op.drop_index(op.f('ix_monthlyindicator_id'), table_name='monthlyindicator')
    op.drop_table('monthlyindicator')
    # ### end Alembic commands ###
