"""Init migration

Revision ID: 59f86526ba69
Revises: bab55b0925ac
Create Date: 2023-07-06 23:04:14.538332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f86526ba69'
down_revision = 'bab55b0925ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_indicator_country'), 'indicator', ['country'], unique=False)
    op.create_index(op.f('ix_indicator_period'), 'indicator', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicator_period'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_country'), table_name='indicator')
    # ### end Alembic commands ###
